### ISSUE TITLE
Code Review #2

### ISSUE THREAD

**Issue by jeremylombogia** [maulanarasoky/JAVA#2]
https://github.com/maulanarasoky/Java/blob/d5dff1a6c77f6ace002b984221c8b3829b08e849/Single%20Linked%20List/src/com/company/Elements.java#L4

https://github.com/maulanarasoky/Java/blob/d5dff1a6c77f6ace002b984221c8b3829b08e849/Single%20Linked%20List/src/com/company/Elements.java#L5

https://github.com/maulanarasoky/Java/blob/d5dff1a6c77f6ace002b984221c8b3829b08e849/Single%20Linked%20List/src/com/company/Function.java#L5

You should put access modifier level in the first word, example: `public String employeeId`

https://github.com/maulanarasoky/Java/blob/d5dff1a6c77f6ace002b984221c8b3829b08e849/Single%20Linked%20List/src/com/company/Main.java#L4

Comment like this should be in the top of code.

More review updated soon.

**Comment by maulanarasoky** [comment]
I've tried what you told me to do, but my code that was originally a green checklist has become like this. why is that?
![image](https://user-images.githubusercontent.com/42926442/52907625-af0fa780-3297-11e9-9421-2ad5f7d6c383.png)
