### ISSUE TITLE
Don't Repeat Yourself

### ISSUE THREAD

**Issue by BlinfoldKing** [maulanarasoky/JAVA#3]
https://github.com/maulanarasoky/Java/blob/7d0b4abbe90b0ecc776c48118a30741542d1ddb0/Double%20Linked%20List/src/com/company/Linked.java#L368-L370

``` ((Elements) node.getData()) ``` is being repeated i suggest you assign this value to some variable first

**Comment by maulanarasoky** [comment]
I have changed the code, please review my code again
