### ISSUE TITLE
Code Review #3

### ISSUE THREAD

**Issue by jeremylombogia** [maulanarasoky/JAVA#4]
Hi @maulanarasoky, in this line of code you put _public_, 
https://github.com/maulanarasoky/Java/blob/457000a19d249d40338f27b6b188220117940b95/Double%20Linked%20List/src/com/company/LinkedList.java#L27

but you weren't put the access modifier here
https://github.com/maulanarasoky/Java/blob/457000a19d249d40338f27b6b188220117940b95/Double%20Linked%20List/src/com/company/LinkedList.java#L35

Remember, be consistent @maulanarasoky.

Put _this_ instead of _data_ only here, for better understanding.
https://github.com/maulanarasoky/Java/blob/811ce5d99441be4282f00c2d77c8f26d85bee206/Double%20Linked%20List/src/com/company/LinkedList.java#L24

Overall is good, your code skills boosted in just months 🎉.

**Comment by jeremylombogia** [comment]
One more @maulanarasoky, put README.md should be good for documentation of your repo.

This is a good example of README.md template: 
https://gist.github.com/auth/github?return_to=https%3A%2F%2Fgist.github.com%2FPurpleBooth%2F109311bb0361f32d87a2

**Comment by maulanarasoky** [comment]
sorry, method public void setData (T data) is not in use, I forgot to delete it.
If i put _access _modifier in here, it's gonna be like this. but my code that was originally a green checklist has become like this.
![image](https://user-images.githubusercontent.com/42926442/52907679-c307d900-3298-11e9-8fd2-15d34caaad85.png)
![image](https://user-images.githubusercontent.com/42926442/52907681-ce5b0480-3298-11e9-960a-fe73c258f604.png)
